### ISSUE TITLE
Resource is not a constructor error

### ISSUE THREAD

**Issue by soudaburger** [googleapis/nodejs-resource#84]
Thanks for stopping by to let us know something could be better!

Please run down the following list and make sure you've tried the usual "quick
fixes":

  - Search the issues already opened: https://github.com/googleapis/nodejs-resource/issues
  - Search the issues on our "catch-all" repository: https://github.com/GoogleCloudPlatform/google-cloud-node
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

If you are still having issues, please be sure to include as much information as
possible:

#### Environment details

  - OS: OSX
  - Node.js version: v10.10.0
  - npm version: 6.4.1
  - `@google-cloud/resource` version: 0.8.1

#### Steps to reproduce

  1. Follow example documentation, receive error about "Resource is not a constructor.
  2. https://github.com/googleapis/nodejs-resource/blob/master/samples/projects.js#L21
  3 . The line above should read `const Resource = require('@google-cloud/resource');`.  Notice the curly braces have been removed.

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by JustinBeckwith** [comment]
Greetings!  We need to cut a new release so that these are up to date.
