### ISSUE TITLE
Requiring @google-cloud/resource in React fails

### ISSUE THREAD

**Issue by soudaburger** [googleapis/nodejs-resource#85]
Thanks for stopping by to let us know something could be better!

Please run down the following list and make sure you've tried the usual "quick
fixes":

  - Search the issues already opened: https://github.com/googleapis/nodejs-resource/issues
  - Search the issues on our "catch-all" repository: https://github.com/GoogleCloudPlatform/google-cloud-node
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

If you are still having issues, please be sure to include as much information as
possible:

#### Environment details

  - OS: OSX
  - Node.js version: v10.10.0
  - npm version: 6.4.1
  - `@google-cloud/resource` version: 0.8.1

#### Steps to reproduce

For React:
  1. npm i --save @google-cloud/resource
  2. const Resource = require('@google-cloud/resource'); // Add this to necessary js file
3. npm start

When I include the `@google-cloud/resource` in nodejs and run from CLI, things work fine.
When I include the `@google-cloud/resource` in a React App, it completely crashes.

Ultimately, all I am trying to do is list the projects in my organization.  `@google-cloud/compute` appears to function as expected, but not `@google-cloud/resource`.

Any insight into proper solutions or documentation would be great!  Thanks!

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by JustinBeckwith** [comment]
Greetings!  Currently this library doesn't support the browser.  It's absolutely something we're looking to do though!

**Comment by stephenplusplus** [comment]
I'm going to close and link [this issue](https://github.com/googleapis/google-cloud-node/issues/531), which will definitely be updated when we have support!
