### ISSUE TITLE
System tests are failing

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-resource#95]
The system tests are currently failing with the error:

```
 1) Resource
       lifecycle
         "before all" hook:
     Error: Service accounts cannot create projects without a parent.
      at new ApiError (node_modules/@google-cloud/common/src/util.ts:179:5)
      at Util.parseHttpRespBody (node_modules/@google-cloud/common/src/util.ts:353:32)
      at Util.handleResp (node_modules/@google-cloud/common/src/util.ts:291:22)
      at /Users/beckwith/Code/nodejs-resource/node_modules/@google-cloud/common/src/util.ts:634:14
      at onResponse (node_modules/retry-request/index.js:200:7)
      at /Users/beckwith/Code/nodejs-resource/node_modules/teeny-request/src/index.ts:104:36
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by JustinBeckwith** [comment]
@stephenplusplus you likely have the most context here.  Can you please take a look?

**Comment by stephenplusplus** [comment]
This "parent" concept is new to me. I went to dig in, and it looks like the API has passed us by a bit-- we're at v1, and there's a v2 now. Evidently, there's a new concept, "Organizations" (among others), which we don't have any methods/classes written for. An organization or a "folder" is what is expected as a parent, but I'm not sure a Service Account can have one. And it doesn't look like there are API endpoints to create them-- they are driven by UI actions when logged in as a Google Suite *or* a Cloud Identity account holder: https://cloud.google.com/resource-manager/docs/creating-managing-organization

Any ideas?

**Comment by JustinBeckwith** [comment]
@stephenplusplus It would be nice to get this lib updated to make it functional again :) Right now we can't ship an update.

**Comment by stephenplusplus** [comment]
@JustinBeckwith I believe this will have to be set up from a `long-door-651` project owner.

**Comment by stephenplusplus** [comment]
Thanks for that info @lukwam. To confirm, from the point of view of our integration tests, are these the steps to get started?:

![image](https://user-images.githubusercontent.com/723048/48649285-221b3080-e9c0-11e8-861c-34eea05979e9.png)

- We need to sign up for a Cloud Identity account (or, maybe there is one somewhere else already?)
- We then use the Admin Console to create a service account that has the Project Creator permission

**Comment by lukwam** [comment]
Yes, if you have a domain name, you can sign up for Cloud Identify for free. This will create a Organization for your domain and then you can create Cloud Identity users in that domain, just like in a G Suite domain, but without Gmail/Calendar/Docs/Hangouts/etc. If any of those users create a project, it will be IN the org and there is no way for one of those users to create a project that isn't in your org. And if you create a service account, you could grant that service account the **Project Creator** role in that Organization and then it can create projects with the Org (or one of it's folders) as the parent.

**Comment by dferber90** [comment]
I've got Cloud Identity & a service account set up and would like to programmatically create a project (inside a folder). However I struggle to find an API which lets me specify a parent folder.

I am currently using

```js
// using v0.9.0
const { Resource } = require("@google-cloud/resource");

// create a project
const resource = new Resource();
const project = resource.project("seeder-customer-project-123");

await project
  .create()
  .then(data => {
    const project = data[0];
    const operation = data[1];
    const apiResponse = data[2];

    return operation.promise();
  })
  .then(data => {
    const operationMetadata = data[0];
    console.log("Project created successfully!");
  });
```

I end up with the error message mentioned above:

```js
Error: Service accounts cannot create projects without a parent.
```

which I picked from the docs in the source code. I do have other things like listing projects working though.

@JustinBeckwith I'm confused as this issue was closed without a status update.

Has support for specifying parents been added (am I missing how to use the package correctly) or should I use the REST API directly instead? Could you point me in the right direction of how to achieve this (from node)?

**Comment by asafyish** [comment]
@dferber90 Did you found a solution to this problem ? I am having it as well.

**Comment by JustinBeckwith** [comment]
Greetings folks!  If you're still having issues, please make sure to open a new bug :)

**Comment by dferber90** [comment]
@asafyish I think I ended up using the REST API. I'm not sure as it's been a year and that project has been abandoned since.
